### PR TITLE
Edit Dialog Default Spinner Value |  Shared Preference Value is Validation

### PR DESCRIPTION
**Pull request by maheswaranapk**
1. Edit Dialog launches with Selected Preference Data Type in Spinner.
2. On Pressing "Set" Button, Before setting new value to Shared Preference Value is Validated.

### CODE REVIEW

**Comment by PrashamTrivedi** [comment]
Hi, Sorry for delay..

Your fork currently in consideration, I am planning to test it this weekend. If all goes well it should be uploaded to maven central by wednesday...

**Comment by PrashamTrivedi** [comment]
Some test results
1. When I change type to long it asks me to enter true/false, which should not be the case. Even for boolean I would prefer switches rather than a dialog.
2. Just from reviewing the code I can say there should be a better approach to detect validation, a generic exception is a bad idea, in any exception this code will show an error which it should not.

I will be waiting for better fix from your side.

**Comment by maheswaranapk** [comment]
Hi Dude,

Thank you so much for spending your time.

The problem on asking true/false from Long exists in  Current Master. Check the Below Screen shot

rsz_1rsz_screenshot_from_2015-07-20_124908

Reason : In Spinner
 0 - String 
1 - Int
2 - Long
3 - Boolean
4 - Float

In Code, If selected item is 2, then 
1. Edit Text is made not focusable
2. And onClick Listener is set to launch trueFalseBuilder.

I solved the issue in my version by having a constant public static final int SPINNER_BOOLEAN = 3; in SharedPreferenceUtils.java

Yeah, My Friends too already told me Validation logic what i followed is not a Good practice.

**Comment by PrashamTrivedi** [comment]
Just realized that long issue can be a masters bad coding. I will look into it, and will update the version accordingly. 

For the validation by exception I will try to reproduce the exception it self. I will be updating main code for some small trivial changes, I am working on to introduce a method which will validate the type itself. Right now according to me the best approach is to call appropriate get method (getLong or getString) and check whether a ClassCastException occurs or not, this will be the best approach in my opinion.

If you know how to enter a wrong value or you have any test case regarding to that reply me as soon as possible, I am looking to add some test cases anyway. 

And yes, idea behind your PR is an awesome value addition. I will solve the issues from master and looking forward to merge this as soon as possible.

**Comment by maheswaranapk** [comment]
Sorry Dude, I am not aware of writing Test Cases in Code.

I tested only by manual input as below,
Eg: Select Long in Spinner, Enter a value greater than Long Maximize value ["9,223,372,036,854,775,807"] and Try to Save it.

This is how, I tested it.

If u need any other help, Please ping me.

Instead If you merge my PR, few problems are fixed in it. Just try the code directly from my fork, I think It solve some problem.

Thank u.

**Comment by PrashamTrivedi** [comment]
Right now I am working on your fork, I will do some needed changes and then will merge to master branch. And then I will do some planned stuff.

**Comment by PrashamTrivedi** [comment]
Lot of enhancements made in this library, with your point #1 included. And discussing with you I have discovered some crucial bugs and updated other things. Thanks for your contribution, version 2.2 with this change is being uploaded in maven central

**Comment by maheswaranapk** [comment]
Cool Dude.

**Pull request closed without merging**
