### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by ggajews**
The main reason behind this cleanup is that ic_launcher icon can interfere with your main project, and can be displayed instead of your original icon on debug builds

### CODE REVIEW

**Comment by PrashamTrivedi** [comment]
Thanks for the pull request.

Let's hope it does not have any issues in merging. I will look into it as soon as possible.

**Comment by ggajews** [comment]
@PrashamTrivedi any updates on that?

**Comment by PrashamTrivedi** [comment]
Yet to see.

**Comment by PrashamTrivedi** [comment]
All things look OK, and in my impression this should not produce any errors. I will still run this code locally by tomorrow and if nothing is problematic, I will release the changes as soon as possible, Thanks. :+1:

**Pull request merged**
